meu-teste:
	python AnalisadorSintatico.py ./testes-exp/meu-teste.exp

main:
	python AnalisadorSintatico.py ./testes-exp/teste-001.exp
	python AnalisadorSintatico.py ./testes-exp/teste-002.exp
	python AnalisadorSintatico.py ./testes-exp/teste-003.exp
	python AnalisadorSintatico.py ./testes-exp/teste-004.exp
	python AnalisadorSintatico.py ./testes-exp/teste-006.exp
	python AnalisadorSintatico.py ./testes-exp/teste-007.exp
	python AnalisadorSintatico.py ./testes-exp/teste-008.exp
	python AnalisadorSintatico.py ./testes-exp/teste-009.exp
	python AnalisadorSintatico.py ./testes-exp/teste-010.exp