CC = gcc 			# compilador
execfile = -o main 	# criação do arquivo executavel
CFLAGS=-I.
LINK_FOR_LIB = -lm

# primeiro exercício
first:
	$(CC) exec01.c $(execfile)

# segundo exercício - letra a
second-a:
	$(CC) exec02_a.c $(execfile)

second-b:
	$(CC) exec02_b.c $(execfile) $(LINK_FOR_LIB)