CC = gcc 			# compilador
execfile = -o main 	# criação do arquivo executavel

# primeiro exercício
first:
	$(CC) exec01.c $(execfile)

# segundo exercício - letra a
second-a:
	$(CC) exec02_a.c $(execfile)