CC = gcc -Wall

PROGS = exec_a

all: $(PROGS)

# Para excluir os arquivos gerados na compilação
clean:
	rm -f $(PROGS)

# Para a compilação do exercicio a
a_sinais:	a_sinais.cpp
	$(CC) a_sinais.cpp -o exec_a